sonar.organization=hospola
sonar.projectKey=hospola_FloodSim-Visualizers

sonar.sources=python/visualizer,viewer_net/src
sonar.tests=python/tests/visualizer,viewer_net/tests

sonar.exclusions=**/bin/**,**/obj/**,**/publish/**,**/__pycache__/**,**/.venv/**,python/visualizer/tools/emulator_package/**

sonar.coverage.exclusions=**/PlayerAssets/js/**,**/tools/x3d_player/static/js/**

sonar.python.version=3.12

sonar.python.coverage.reportPaths=.coverage-reports/python/coverage.xml
sonar.cs.cobertura.reportsPaths=.coverage-reports/dotnet/**/coverage.cobertura.xml
