sonar.organization=hospola
sonar.projectKey=hospola_FloodSim-Visualizers

sonar.sources=python/visualizer,viewer_net/src
sonar.tests=python/tests/visualizer,viewer_net/tests

sonar.exclusions=**/bin/**,**/obj/**,**/publish/**,**/__pycache__/**,**/.venv/**,python/visualizer/tools/emulator_package/**

sonar.python.version=3.12
