from typing import Protocol


class SimulationEventHandler(Protocol):
    def handle_event(self, event: dict) -> None: ...
    def on_idle(self) -> None: ...
    def close(self) -> None: ...


class ControlPublisher(Protocol):
    def publish_chunk_ack(self) -> None: ...
